const api = [
    { id: 1, src: './comicbooks/comic.jpg', category: 'comicbooks', title: 'my hero academia', story: 'lorem ipsum sit amet. Est doloremque temporibus et quia eligendi rem sit amet. Est doloremque temporibus et quia eligendi rem sit amet. Est doloremque temporibus et quia eligendi rem sit amet. Est doloremque temporibus et quia eligendi remsit amet. Est doloremque temporibus et quia eligendi rem lorem ipsum sit amet. Est doloremque temporibus et quia eligendi'},
    { id: 2, src: './sales/sales9.jpg', category: 'sales', title: 'the habits of highly effective people' , story: 'lorem ipsum sit amet. Est doloremque temporibus et quia eligendi rem sit amet. Est doloremque temporibus et quia eligendi rem sit amet. Est doloremque temporibus et quia eligendi rem sit amet. Est doloremque temporibus et quia eligendi remsit amet. Est doloremque temporibus et quia eligendi rem '},
    { id: 3, src: './comicbooks/wonder woman.jpg', category: 'comicbooks', title: 'wonderwoman' , story: 'lorem ipsum sit amet. Est doloremque temporibus et quia eligendi rem sit amet. Est doloremque temporibus et quia eligendi rem sit amet. Est doloremque temporibus et quia eligendi rem sit amet. Est doloremque temporibus et quia eligendi remsit amet. Est doloremque temporibus et quia eligendi rem Est doloremque temporibus et quia eligendi rem sit amet'},
    { id: 4, src: './motivation/book2.jpg', category: 'motivation', title: 'make your bed' , story: 'lorem ipsum sit amet. Est doloremque temporibus et quia eligendi rem sit amet. Est doloremque temporibus et quia eligendi rem sit amet. Est doloremque temporibus et quia eligendi rem sit amet. Est doloremque temporibus et quia eligendi remsit amet. Est doloremque temporibus et quia eligendi rem Est doloremque temporibus et quia eligendi rem sit amet'},
   
    { id: 5, src: './sales/sales3.jpg', category: 'sales', title: 'emotional intelligence' , story: 'lorem ipsum sit amet. Est doloremque temporibus et quia eligendi rem sit amet. Est doloremque temporibus et quia eligendi rem sit amet. Est doloremque temporibus et quia eligendi rem sit amet. Est doloremque temporibus et quia eligendi remsit amet. Est doloremque temporibus et quia eligendi rem Est doloremque temporibus et quia eligendi rem sit amet'},
    { id: 6, src: './comicbooks/superman.jpg', category: 'comicbooks', title: 'superman' , story: 'lorem ipsum sit amet. Est doloremque temporibus et quia eligendi rem sit amet. Est doloremque temporibus et quia eligendi rem sit amet. Est doloremque temporibus et quia eligendi rem sit amet. Est doloremque temporibus et quia eligendi remsit amet. Est doloremque temporibus et quia eligendi rem Est doloremque temporibus et quia eligendi rem sit amet'},
    { id: 7, src: './motivation/book1.png', category: 'motivation', title: 'the power of positive thinking' , story: 'lorem ipsum sit amet. Est doloremque temporibus et quia eligendi rem sit amet. Est doloremque temporibus et quia eligendi rem sit amet. Est doloremque temporibus et quia eligendi rem sit amet. Est doloremque temporibus et quia eligendi remsit amet. Est doloremque temporibus et quia eligendi rem Est doloremque temporibus et quia eligendi rem sit amet'},
 
    { id: 8, src: './sales/sales10.jpg', category: 'sales', title: 'think and grow rich' , story: 'lorem ipsum sit amet. Est doloremque temporibus et quia eligendi rem sit amet. Est doloremque temporibus et quia eligendi rem sit amet. Est doloremque temporibus et quia eligendi rem sit amet. Est doloremque temporibus et quia eligendi remsit amet. Est doloremque temporibus et quia eligendi rem Est doloremque temporibus et quia eligendi rem sit amet'},
    { id: 9, src: './comicbooks/comic2.jpg', category: 'comicbooks', title: 'astro boy' , story: 'lorem ipsum sit amet. Est doloremque temporibus et quia eligendi rem sit amet. Est doloremque temporibus et quia eligendi rem sit amet. Est doloremque temporibus et quia eligendi rem sit amet. Est doloremque temporibus et quia eligendi remsit amet. Est doloremque temporibus et quia eligendi rem Est doloremque temporibus et quia eligendi rem sit amet'},
    { id: 10, src: './motivation/book4.jpg', category: 'motivation', title: 'choose yourself' , story: 'lorem ipsum sit amet. Est doloremque temporibus et quia eligendi rem sit amet. Est doloremque temporibus et quia eligendi rem sit amet. Est doloremque temporibus et quia eligendi rem sit amet. Est doloremque temporibus et quia eligendi remsit amet. Est doloremque temporibus et quia eligendi rem Est doloremque temporibus et quia eligendi rem sit amet'},
  
    { id: 11, src: './sales/sales6.jpg', category: 'sales', title: 'simple sales solution' , story: 'lorem ipsum sit amet. Est doloremque temporibus et quia eligendi rem sit amet. Est doloremque temporibus et quia eligendi rem sit amet. Est doloremque temporibus et quia eligendi rem sit amet. Est doloremque temporibus et quia eligendi remsit amet. Est doloremque temporibus et quia eligendi rem Est doloremque temporibus et quia eligendi rem sit amet'},
    { id: 12, src: './comicbooks/comic3.jpg', category: 'comicbooks', title: 'demon slayer' , story: 'lorem ipsum sit amet. Est doloremque temporibus et quia eligendi rem sit amet. Est doloremque temporibus et quia eligendi rem sit amet. Est doloremque temporibus et quia eligendi rem sit amet. Est doloremque temporibus et quia eligendi remsit amet. Est doloremque temporibus et quia eligendi rem Est doloremque temporibus et quia eligendi rem sit amet'},
    { id: 13, src: './motivation/book3.jpg', category: 'motivation', title: 'man search for meaning' , story: 'lorem ipsum sit amet. Est doloremque temporibus et quia eligendi rem sit amet. Est doloremque temporibus et quia eligendi rem sit amet. Est doloremque temporibus et quia eligendi rem sit amet. Est doloremque temporibus et quia eligendi remsit amet. Est doloremque temporibus et quia eligendi rem Est doloremque temporibus et quia eligendi rem sit amet'},
    { id: 14, src: './comicbooks/onepiece.jpg', category: 'comicbooks', title: 'onepiece' , story: 'lorem ipsum sit amet. Est doloremque temporibus et quia eligendi rem sit amet. Est doloremque temporibus et quia eligendi rem sit amet. Est doloremque temporibus et quia eligendi rem sit amet. Est doloremque temporibus et quia eligendi remsit amet. Est doloremque temporibus et quia eligendi rem Est doloremque temporibus et quia eligendi rem sit amet'},
    { id: 15, src: './sales/sales5.jpeg', category: 'sales', title: 'the greatest showman in the world' , story: 'lorem ipsum sit amet. Est doloremque temporibus et quia eligendi rem sit amet. Est doloremque temporibus et quia eligendi rem sit amet. Est doloremque temporibus et quia eligendi rem sit amet. Est doloremque temporibus et quia eligendi remsit amet. Est doloremque temporibus et quia eligendi rem Est doloremque temporibus et quia eligendi rem sit amet'},
    { id: 16, src: './comicbooks/comic5.jpg', category: 'comicbooks', title: 'attack of titan' , story: 'lorem ipsum sit amet. Est doloremque temporibus et quia eligendi rem sit amet. Est doloremque temporibus et quia eligendi rem sit amet. Est doloremque temporibus et quia eligendi rem sit amet. Est doloremque temporibus et quia eligendi remsit amet. Est doloremque temporibus et quia eligendi rem Est doloremque temporibus et quia eligendi rem sit amet'},
    { id: 17, src: './motivation/book5.jpg', category: 'motivation', title: 'atomic habits' , story: 'lorem ipsum sit amet. Est doloremque temporibus et quia eligendi rem sit amet. Est doloremque temporibus et quia eligendi rem sit amet. Est doloremque temporibus et quia eligendi rem sit amet. Est doloremque temporibus et quia eligendi remsit amet. Est doloremque temporibus et quia eligendi rem Est doloremque temporibus et quia eligendi rem sit amet'},
    { id: 18, src: './comicbooks/spiderman2.jpg', category: 'comicbooks', title: 'spiderman3' , story: 'lorem ipsum sit amet. Est doloremque temporibus et quia eligendi rem sit amet. Est doloremque temporibus et quia eligendi rem sit amet. Est doloremque temporibus et quia eligendi rem sit amet. Est doloremque temporibus et quia eligendi remsit amet. Est doloremque temporibus et quia eligendi rem Est doloremque temporibus et quia eligendi rem sit amet'},
   
    { id: 19, src: './motivation/motivation11.jpeg', category: 'motivation', title: 'the power of positive thinking' , story: 'lorem ipsum sit amet. Est doloremque temporibus et quia eligendi rem sit amet. Est doloremque temporibus et quia eligendi rem sit amet. Est doloremque temporibus et quia eligendi rem sit amet. Est doloremque temporibus et quia eligendi remsit amet. Est doloremque temporibus et quia eligendi rem Est doloremque temporibus et quia eligendi rem sit amet'},
    { id: 20, src: './comicbooks/comic12.jpg', category: 'comicbooks', title: 'one punch man' , story: 'lorem ipsum sit amet. Est doloremque temporibus et quia eligendi rem sit amet. Est doloremque temporibus et quia eligendi rem sit amet. Est doloremque temporibus et quia eligendi rem sit amet. Est doloremque temporibus et quia eligendi remsit amet. Est doloremque temporibus et quia eligendi rem Est doloremque temporibus et quia eligendi rem sit amet'},
    { id: 21, src: './comicbooks/spider.jpg', category: 'comicbooks', title: 'spider' , story: 'lorem ipsum sit amet. Est doloremque temporibus et quia eligendi rem sit amet. Est doloremque temporibus et quia eligendi rem sit amet. Est doloremque temporibus et quia eligendi rem sit amet. Est doloremque temporibus et quia eligendi remsit amet. Est doloremque temporibus et quia eligendi rem Est doloremque temporibus et quia eligendi rem sit amet'},
    { id: 22, src: './motivation/motivation10.jpg', category: 'motivation', title: 'zero to one' , story: 'lorem ipsum sit amet. Est doloremque temporibus et quia eligendi rem sit amet. Est doloremque temporibus et quia eligendi rem sit amet. Est doloremque temporibus et quia eligendi rem sit amet. Est doloremque temporibus et quia eligendi remsit amet. Est doloremque temporibus et quia eligendi rem Est doloremque temporibus et quia eligendi rem sit amet'},
    { id: 23, src: './sales/sales5.jpeg', category: 'sales', title: 'the greatest salesman in the world' , story: 'lorem ipsum sit amet. Est doloremque temporibus et quia eligendi rem sit amet. Est doloremque temporibus et quia eligendi rem sit amet. Est doloremque temporibus et quia eligendi rem sit amet. Est doloremque temporibus et quia eligendi remsit amet. Est doloremque temporibus et quia eligendi rem Est doloremque temporibus et quia eligendi rem sit amet'},
    { id: 24, src: './comicbooks/wonder woman.jpg', category: 'comicbooks', title: 'wonder' , story: 'lorem ipsum sit amet. Est doloremque temporibus et quia eligendi rem sit amet. Est doloremque temporibus et quia eligendi rem sit amet. Est doloremque temporibus et quia eligendi rem sit amet. Est doloremque temporibus et quia eligendi remsit amet. Est doloremque temporibus et quia eligendi rem Est doloremque temporibus et quia eligendi rem sit amet'},
    { id: 25, src: './comicbooks/comic13.jpg', category: 'comicbooks', title: 'sailor moon' , story: 'lorem ipsum sit amet. Est doloremque temporibus et quia eligendi rem sit amet. Est doloremque temporibus et quia eligendi rem sit amet. Est doloremque temporibus et quia eligendi rem sit amet. Est doloremque temporibus et quia eligendi remsit amet. Est doloremque temporibus et quia eligendi rem Est doloremque temporibus et quia eligendi rem sit amet'},
    
    { id: 26, src: './comicbooks/spider.jpg', category: 'comicbooks', title: 'spider' , story: 'lorem ipsum sit amet. Est doloremque temporibus et quia eligendi rem sit amet. Est doloremque temporibus et quia eligendi rem sit amet. Est doloremque temporibus et quia eligendi rem sit amet. Est doloremque temporibus et quia eligendi remsit amet. Est doloremque temporibus et quia eligendi rem Est doloremque temporibus et quia eligendi rem sit amet'},
    { id: 27, src: './comicbooks/comicbook10.jpg', category: 'comicbooks', title: 'hunter x hunter' , story: 'lorem ipsum sit amet. Est doloremque temporibus et quia eligendi rem sit amet. Est doloremque temporibus et quia eligendi rem sit amet. Est doloremque temporibus et quia eligendi rem sit amet. Est doloremque temporibus et quia eligendi remsit amet. Est doloremque temporibus et quia eligendi rem Est doloremque temporibus et quia eligendi rem sit amet'},
    { id: 28, src: './comicbooks/batman.png', category: 'comicbooks', title: 'batman' , story: 'lorem ipsum sit amet. Est doloremque temporibus et quia eligendi rem sit amet. Est doloremque temporibus et quia eligendi rem sit amet. Est doloremque temporibus et quia eligendi rem sit amet. Est doloremque temporibus et quia eligendi remsit amet. Est doloremque temporibus et quia eligendi rem Est doloremque temporibus et quia eligendi rem sit amet'},
    { id: 29, src: './motivation/motivation12.jpg', category: 'motivation', title: 'how to win friends and influence people' , story: 'lorem ipsum sit amet. Est doloremque temporibus et quia eligendi rem sit amet. Est doloremque temporibus et quia eligendi rem sit amet. Est doloremque temporibus et quia eligendi rem sit amet. Est doloremque temporibus et quia eligendi remsit amet. Est doloremque temporibus et quia eligendi rem Est doloremque temporibus et quia eligendi rem sit amet'},
    { id: 30, src: './comicbooks/captain.jpg', category: 'comicbooks', title: 'captain america' , story: 'lorem ipsum sit amet. Est doloremque temporibus et quia eligendi rem sit amet. Est doloremque temporibus et quia eligendi rem sit amet. Est doloremque temporibus et quia eligendi rem sit amet. Est doloremque temporibus et quia eligendi remsit amet. Est doloremque temporibus et quia eligendi rem Est doloremque temporibus et quia eligendi rem sit amet'},
    { id: 31, src: './comicbooks/superman.jpg', category: 'comicbooks', title: 'superman' , story: 'lorem ipsum sit amet. Est doloremque temporibus et quia eligendi rem sit amet. Est doloremque temporibus et quia eligendi rem sit amet. Est doloremque temporibus et quia eligendi rem sit amet. Est doloremque temporibus et quia eligendi remsit amet. Est doloremque temporibus et quia eligendi rem Est doloremque temporibus et quia eligendi rem sit amet'},
    { id: 32, src: './comicbooks/spiderman2.jpg', category: 'comicbooks', title: 'spiderman2' , story: 'lorem ipsum sit amet. Est doloremque temporibus et quia eligendi rem sit amet. Est doloremque temporibus et quia eligendi rem sit amet. Est doloremque temporibus et quia eligendi rem sit amet. Est doloremque temporibus et quia eligendi remsit amet. Est doloremque temporibus et quia eligendi rem Est doloremque temporibus et quia eligendi rem sit amet'}
  ]

  export const setApi = () => {
      return api;
  }


  export const setComic = () => {
      return api.filter(data => data.category === "comicbooks")
  }

  export const setMotivation = () => {
      return api.filter(motiv => motiv.category === "motivation")
  }
 
  export const setSales = () => {
    return api.filter(data => data.category === "sales")
}